file:
    - 'tests/functional/api/movies/index.js'
    - 'tests/functional/api/actors/index.js'
    - 'tests/functional/api/tvShows/index.js'
    - 'tests/functional/api/users/index.js'
require: '@babel/register'
exit: true
timeout: 4000
